In [1]:
import pandas as pd
import pickle as pkl

In [2]:
df = pd.read_csv('modeling_data.csv')

In [186]:
df

103 st (7)  canal st (6)  96 st (6)  28 st (6)  23 st (6)  110 st (6)  103 st (6)  canal st (1)  23 st (1)  28 st (1)  86 st (1)  96 st (1)  110 st (1)  103 st (1)             date                                        subject                                            message  day_of_week  rush_hour  weekend  2  brooklyn  queens  bronx  manhattan      stations  103 st  110 st  111 st  116 st  125 st  135 st  137 st  138 st-grand concourse  14 st  145 st  148 st  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  23 st  233 st  238 st  241 st  242 st  28 st  33 st  34 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  86 st  90 st  96 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  burke av  burnside  bx park east  \
0               0             0          0          0          0           0           0             0          0          0          0          0           0           0  9/30/2021 21:34                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0   
1               0             0          0          0          0           0           0             0          0          0          0          0           0           0  9/30/2021 21:28                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0   
2               0             0          0          0          0           0           0             0          0          0          0          0           0           0  9/30/2021 19:14                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0  1         0       0      1          0   allerton av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0   
3               0          

In [3]:
df['subject'] = df['subject'].str.lower()

In [4]:
df['message'] = df['message'].str.lower()

In [487]:
df['message'].str.contains('3 av -149').value_counts()

False    67185
True         1
Name: message, dtype: int64

In [6]:
stations_1 = ['van cortlandt', '242 st','238 st','231 st','225 st','215 st','207 st','dyckman st',
              '191 st','181 st','168 st','157 st','145 st','137 st','125 st','116 st', '110 st','103 st',
              '96 st','86 st','79 st','72 st','66 st','columbus','50 st','times sq',
              '34 st','28 st','23 st','18 st','14 st','christopher st','houston st','canal st',
              'franklin st','chambers st','wtc','rector st','ferry']

In [488]:
stations_2 = ['241 st', 'nereid av','233 st','225 st','219 st','gun hill','burke av','allerton av','pelham p','bx park east',
              'e 180', 'e 178','174 st','freeman st','simpson st','intervale av','prospect av','jackson av',
              '3 av-149', '3 av- 149','3 av - 149', '3 av -149', '149 st-grand concourse','149 st - grand concourse','149 st grand concourse',
              '135 st','125 st','116 st','cathedral p','96 st','72 st','times sq','34 st','14 st',
              'chambers st','park pl','fulton st','wall st','clark st','borough hall','hoyt st','nevins st','atlantic av',
              'barclays','bergen st','grand army','eastern p', 'franklin av', 'president st','sterling st',
              'winthrop st','church av','beverly r','newkirk av','flatbush av']

3 av- and 3 av - are same

149 st-grand concourse, 149 st - grand concourse, 149 st grand concourse are same

atlantic av and barclays are same

In [8]:
stations_3 = ['148 st', '145 st','135 st','125 st','116 st','cathedral p','96 st','72 st','times sq','34 st',
              '14 st','chambers st','park pl','fulton st','wall st','clark st','borough hall','hoyt st','nevins st',
              'atlantic av', 'barclays','bergen st','grand army','eastern p', 'franklin av','nostrand av',
              'kingston av','crown heights','crown hts' 'utica av','sutter av',
             'saratoga av','rockaway av','junius st','pennsylvania av','van siclen','new lots']

atlantic av and barclays are same

crown heights, crown hts and utica av are same

In [9]:
stations_4 = ['woodlawn','moshulu','bedford p', 'kingsbridge','fordham','183 st','burnside','176 st',
             'mt eden', 'mount eden', '170 st','167 st','161 st','149 st-grand concourse','149 st - grand concourse',
              '149 st grand concourse', '138 st-grand concourse', '138 st - grand concourse','125 st','86 st','59 st',
             'grand central', 'union sq','brooklyn bridge','fulton st','wall st','bowling green','borough hall',
             'nevins st','atlantic av', 'barclays','franklin av','crown heights','crown hts' 'utica av']

mt eden and mount eden are same

149 st-grand concourse, 149 st - grand concourse, 149 st grand concourse are same

138 st-grand concourse and 138 st - grand concourse are same

atlantic av and barclays are same

crown heights, crown hts and utica av are same

In [10]:
df['message'].str.contains('columbus').value_counts()

False    67033
True       153
Name: message, dtype: int64

In [11]:
stations_5 = ['eastchester','baychester av','gun hill','pelham p','morris','e 180','west farms','174 st','freeman',
             'simpson','intervale av','prospect av','jackson','3 av-','3 av -','149 st-grand concourse',
              '149 st - grand concourse','149 st grand concourse','138 st-grand concourse', '138 st - grand concourse',
             '125 st','86 st','59 st','grand central','union sq','brooklyn bridge','fulton','wall st','bowling green',
             'borough hall','nevins','atlantic av','barclays','franklin av','president st','sterling st','winthrop st',
             'church av','beverly','newkirk av','flatbush av']

3 av- and 3 av - are same

149 st-grand concourse, 149 st - grand concourse, 149 st grand concourse are same

138 st-grand concourse and 138 st - grand concourse are same

atlantic av and barclays are same

4/5/6 59 st is different from 1 59 st columbus circle

In [12]:
stations_6 = ['pelham bay','buhre','middletown','westchester','zerega','castle hill','parkchester','st lawrence',
             'morrison av','elder av','whitlock','hunts point','longwood av','e 149','e 143','cypress av','brook av',
             '3 av 138 st','3 av-138 st', '3 av - 138 st', '3 av- 138 st','3 av -138 st', '125 st','116 st','110 st', '103 st',
             '96 st', '86 st','77 st','68 st','59 st','51 st','grand central','33 st','28 st', '23 st','union sq','astor',
              'bleeker st','spring st','canal st','brooklyn bridge']

3 av 138 st,3 av-138 st, 3 av - 138 st, 3 av- 138 st, and 3 av -138 st are same

different 96 from 1/2/3

different 86 from 1

different 28 from 1

different 23 from 1

different canal from 1

In [13]:
stations_7 = ['flushing', 'mets','111 st','103 st','junction b', '90 st','82 st','74 st','69 st',
             '61 st','52 st','46 st','40 st','rawson','qnsboro pl','court sq','hunters p','vernon b',
             'grand central','5 av','times sq','34 st h', '34 st-h','34 st- h','34 st - h']

34 st h, 34 st-h, 34 st- h, 34 st - h are same

In [14]:
df['message'].str.contains('34 st- h').value_counts()

False    67180
True         6
Name: message, dtype: int64

In [15]:
df = df.loc[~df['subject'].str.contains('planned|Planned')]

In [16]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [17]:
len(stations_1)

39

In [18]:
irt_stations = (stations_1+stations_2+stations_3+stations_4+stations_5+stations_6+stations_7)

In [61]:
irt_stations = ['van cortlandt', '242 st', '238 st', '231 st', '225 st', '215 st', '207 st', 'dyckman st', '191 st',
                '181 st', '168 st', '157 st', '145 st', '137 st', '125 st (1/2/3)', '116 st (1)', '110 st (1)',
                '103 st (1)', '96 st (1)','86 st (1)', '79 st', '72 st', '66 st', 'columbus', '50 st', 'times sq', '34 st',
                '28 st (1)', '23 st (1)','18 st', '14 st', 'christopher st', 'houston st', 'canal st (1)',
                'franklin st', 'chambers st', 'wtc', 'rector st', 'ferry', '241 st', 'nereid av',
                '233 st', '225 st', '219 st', 'gun hill (2/5)','burke av', 'allerton av', 'pelham p', 'bx park east',
                'e 180', 'e 178', '174 st', 'freeman st','simpson st', 'intervale av', 'prospect av',
                'jackson av', '3 av-149 st' '149 st-grand concourse','135 st', '125 st', '116 st', 'cathedral pkwy-110 st',
                'park pl', 'fulton st (2/3)', 'wall st (2/3)','clark st', 'borough hall', 'hoyt st', 'nevins st',
                'atlantic av-barclays ctr', 'bergen st', 'grand army plza','eastern pkwy', 'franklin av', 'president st',
                'sterling st', 'winthrop st', 'church av', 'beverly rd', 'newkirk av', 'flatbush av', '148 st',
                'nostrand av', 'kingston av', 'crown hts-utica av','sutter av', 'saratoga av', 'rockaway av', 'junius st',
                'pennsylvania av', 'van siclen', 'new lots','woodlawn', 'moshulu', 'bedford p', 'kingsbridge', 'fordham',
                '183 st', 'burnside', '176 st', 'mt eden', '170 st', '167 st', '161 st', '138 st-grand concourse',
                '125 st (4/5/6)', '86 st (4/5/6)', '59 st','grand central', 'union sq', 'brooklyn bridge', 'fulton st (4/5)',
                'wall st (4/5)', 'bowling green','eastchester', 'baychester av', 'gun hill (5)', 'pelham pkwy',
                'morris park', 'pelham bay', 'buhre av','middletown rd', 'westchester sq', 'zerega av', 'castle hill av',
                'parkchester', 'st lawrence av','morrison av', 'elder av', 'whitlock av', 'hunts point av', 'longwood av',
                'e 149 st', 'e 143 st','cypress av', 'brook av', '3 av-138 st', '116 st (6)', '110 st (6)', '103 st (6)',
                '96 st (6)','77 st', '68 st','51 st', '33 st', '28 st (6)', '23 st (6)', 'astor pl', 'bleeker st', 'spring st',
                'canal st (6)', 'flushing main st', 'mets-willis pt', '111 st', '103 st (7)', 'junction b', '90 st', '82 st',
                '74 st', '69 st', '61 st', '52 st', '46 st', '40 st', 'rawson st', 'qnsboro plza', 'court sq', 'hunters pt',
                'vernon blvd', '5 av', '34 st-herald sq']

In [20]:
df

date                                        subject  \
0      9/30/2021 21:34                 update : bx   2 train   delays   
1      9/30/2021 21:28                          bx   2 train   delays   
2      9/30/2021 19:14                 update : bx   2 train   delays   
3      9/30/2021 19:10                          bx   2 train   delays   
4      9/30/2021 18:48        update : bx   2 train   trains rerouted   
...                ...                                            ...   
67181    1/2/2010 8:28              qns   7 train   track maintenance   
67182    1/1/2010 0:56  updated : bx   4 train   police investigation   
67183    1/1/2010 0:49  updated : bx   4 train   police investigation   
67184    1/1/2010 0:35  updated : bx   4 train   police investigation   
67185    1/1/2010 0:26            bx   4 train   police investigation   

                                                 message  day_of_week  \
0      2 trains are proceeding with delays after our ...            3   
1      2 trains are delayed in both directions while ...            3   
2      southbound 2 trains are proceeding after we mo...            3   
3      southbound 2 trains are delayed while we inves...            3   
4      wakefield-bound 2 trains have resumed stopping...            3   
...                                                  ...          ...   
67181  times sq-bound 7 trains operating on normal ro...            5   
67182  4 train service has resumed with residual delays.            4   
67183  bk-bound. 4 train express burnside av to 125 s...            4   
67184  both directions. 4 train susp btwn burnside av...            4   
67185  bk-bound. 4 train via express track burnside a...            4   

       rush_hour  weekend  2  brooklyn  queens  bronx  manhattan  
0              0        0  1         0       0      1          0  
1              0        0  1         0       0      1          0  
2              0        0  1         0       0      1          0  
3              0        0  1         0       0      1          0  
4              0        0  1         0       0      1          0  
...          ...      ... ..       ...     ...    ...        ...  
67181          0        1  0         0       1      0          0  
67182          0        0  0         0       0      1          0  
67183          0        0  0         0       0      1          0  
67184          0        0  0         0       0      1          0  
67185          0        0  0         0       0      1          0  

[67186 rows x 11 columns]

In [21]:
irt_stations = sorted(irt_stations)

In [22]:
irt_stations_df = pd.DataFrame(index=pd.Series(0),columns=irt_stations)

In [23]:
irt_stations_df

103 st (1) 103 st (6) 103 st (7) 110 st (1) 110 st (6) 111 st 116 st  \
0        NaN        NaN        NaN        NaN        NaN    NaN    NaN   

  116 st (1) 116 st (6) 125 st  ... van siclen vernon blvd wall st (2/3)  \
0        NaN        NaN    NaN  ...        NaN         NaN           NaN   

  wall st (4/5) westchester sq whitlock av winthrop st woodlawn  wtc zerega av  
0           NaN            NaN         NaN         NaN      NaN  NaN       NaN  

[1 rows x 170 columns]

In [24]:
df.head()

date                                  subject  \
0  9/30/2021 21:34           update : bx   2 train   delays   
1  9/30/2021 21:28                    bx   2 train   delays   
2  9/30/2021 19:14           update : bx   2 train   delays   
3  9/30/2021 19:10                    bx   2 train   delays   
4  9/30/2021 18:48  update : bx   2 train   trains rerouted   

                                             message  day_of_week  rush_hour  \
0  2 trains are proceeding with delays after our ...            3          0   
1  2 trains are delayed in both directions while ...            3          0   
2  southbound 2 trains are proceeding after we mo...            3          0   
3  southbound 2 trains are delayed while we inves...            3          0   
4  wakefield-bound 2 trains have resumed stopping...            3          0   

   weekend  2  brooklyn  queens  bronx  manhattan  
0        0  1         0       0      1          0  
1        0  1         0       0      1          0  
2        0  1         0       0      1          0  
3        0  1         0       0      1          0  
4        0  1         0       0      1          0

In [25]:
#df = df.merge(irt_stations_df,how='outer', left_index=True,right_index=True)

In [26]:
pd.set_option('display.max_columns',None)

In [27]:
df

date                                        subject  \
0      9/30/2021 21:34                 update : bx   2 train   delays   
1      9/30/2021 21:28                          bx   2 train   delays   
2      9/30/2021 19:14                 update : bx   2 train   delays   
3      9/30/2021 19:10                          bx   2 train   delays   
4      9/30/2021 18:48        update : bx   2 train   trains rerouted   
...                ...                                            ...   
67181    1/2/2010 8:28              qns   7 train   track maintenance   
67182    1/1/2010 0:56  updated : bx   4 train   police investigation   
67183    1/1/2010 0:49  updated : bx   4 train   police investigation   
67184    1/1/2010 0:35  updated : bx   4 train   police investigation   
67185    1/1/2010 0:26            bx   4 train   police investigation   

                                                 message  day_of_week  \
0      2 trains are proceeding with delays after our ...            3   
1      2 trains are delayed in both directions while ...            3   
2      southbound 2 trains are proceeding after we mo...            3   
3      southbound 2 trains are delayed while we inves...            3   
4      wakefield-bound 2 trains have resumed stopping...            3   
...                                                  ...          ...   
67181  times sq-bound 7 trains operating on normal ro...            5   
67182  4 train service has resumed with residual delays.            4   
67183  bk-bound. 4 train express burnside av to 125 s...            4   
67184  both directions. 4 train susp btwn burnside av...            4   
67185  bk-bound. 4 train via express track burnside a...            4   

       rush_hour  weekend  2  brooklyn  queens  bronx  manhattan  
0              0        0  1         0       0      1          0  
1              0        0  1         0       0      1          0  
2              0        0  1         0       0      1          0  
3              0        0  1         0       0      1          0  
4              0        0  1         0       0      1          0  
...          ...      ... ..       ...     ...    ...        ...  
67181          0        1  0         0       1      0          0  
67182          0        0  0         0       0      1          0  
67183          0        0  0         0       0      1          0  
67184          0        0  0         0       0      1          0  
67185          0        0  0         0       0      1          0  

[67186 rows x 11 columns]

In [28]:
df

date                                        subject  \
0      9/30/2021 21:34                 update : bx   2 train   delays   
1      9/30/2021 21:28                          bx   2 train   delays   
2      9/30/2021 19:14                 update : bx   2 train   delays   
3      9/30/2021 19:10                          bx   2 train   delays   
4      9/30/2021 18:48        update : bx   2 train   trains rerouted   
...                ...                                            ...   
67181    1/2/2010 8:28              qns   7 train   track maintenance   
67182    1/1/2010 0:56  updated : bx   4 train   police investigation   
67183    1/1/2010 0:49  updated : bx   4 train   police investigation   
67184    1/1/2010 0:35  updated : bx   4 train   police investigation   
67185    1/1/2010 0:26            bx   4 train   police investigation   

                                                 message  day_of_week  \
0      2 trains are proceeding with delays after our ...            3   
1      2 trains are delayed in both directions while ...            3   
2      southbound 2 trains are proceeding after we mo...            3   
3      southbound 2 trains are delayed while we inves...            3   
4      wakefield-bound 2 trains have resumed stopping...            3   
...                                                  ...          ...   
67181  times sq-bound 7 trains operating on normal ro...            5   
67182  4 train service has resumed with residual delays.            4   
67183  bk-bound. 4 train express burnside av to 125 s...            4   
67184  both directions. 4 train susp btwn burnside av...            4   
67185  bk-bound. 4 train via express track burnside a...            4   

       rush_hour  weekend  2  brooklyn  queens  bronx  manhattan  
0              0        0  1         0       0      1          0  
1              0        0  1         0       0      1          0  
2              0        0  1         0       0      1          0  
3              0        0  1         0       0      1          0  
4              0        0  1         0       0      1          0  
...          ...      ... ..       ...     ...    ...        ...  
67181          0        1  0         0       1      0          0  
67182          0        0  0         0       0      1          0  
67183          0        0  0         0       0      1          0  
67184          0        0  0         0       0      1          0  
67185          0        0  0         0       0      1          0  

[67186 rows x 11 columns]

In [29]:
def get_one(value):
    if value is True:
        return 1
    else:
        return 0

In [30]:
pd.set_option('display.width',1000)

In [489]:
irt_lookup = (stations_1+stations_2+stations_3+stations_4+stations_5+stations_6+stations_7)

In [490]:
irt_lookup

['van cortlandt',
 '242 st',
 '238 st',
 '231 st',
 '225 st',
 '215 st',
 '207 st',
 'dyckman st',
 '191 st',
 '181 st',
 '168 st',
 '157 st',
 '145 st',
 '137 st',
 '125 st',
 '116 st',
 '110 st',
 '103 st',
 '96 st',
 '86 st',
 '79 st',
 '72 st',
 '66 st',
 'columbus',
 '50 st',
 'times sq',
 '34 st',
 '28 st',
 '23 st',
 '18 st',
 '14 st',
 'christopher st',
 'houston st',
 'canal st',
 'franklin st',
 'chambers st',
 'wtc',
 'rector st',
 'ferry',
 '241 st',
 'nereid av',
 '233 st',
 '225 st',
 '219 st',
 'gun hill',
 'burke av',
 'allerton av',
 'pelham p',
 'bx park east',
 'e 180',
 'e 178',
 '174 st',
 'freeman st',
 'simpson st',
 'intervale av',
 'prospect av',
 'jackson av',
 '3 av-149',
 '3 av- 149',
 '3 av - 149',
 '3 av -149',
 '149 st-grand concourse',
 '149 st - grand concourse',
 '149 st grand concourse',
 '135 st',
 '125 st',
 '116 st',
 'cathedral p',
 '96 st',
 '72 st',
 'times sq',
 '34 st',
 '14 st',
 'chambers st',
 'park pl',
 'fulton st',
 'wall st',
 'clark st

In [33]:
def add_at(list, str):
    str += '{0}'
    list = [str.format(i) for i in list]
    return list

In [491]:
irt_lookup = add_at(irt_lookup,'at ')

In [35]:
names = list(irt_stations_df.columns)

In [36]:
names

['103 st (1)',
 '103 st (6)',
 '103 st (7)',
 '110 st (1)',
 '110 st (6)',
 '111 st',
 '116 st',
 '116 st (1)',
 '116 st (6)',
 '125 st',
 '125 st (1/2/3)',
 '125 st (4/5/6)',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '191 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '225 st',
 '23 st (1)',
 '23 st (6)',
 '231 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '28 st (1)',
 '28 st (6)',
 '3 av-138 st',
 '3 av-149 st149 st-grand concourse',
 '33 st',
 '34 st',
 '34 st-herald sq',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '86 st (1)',
 '86 st (4/5/6)',
 '90 st',
 '96 st (1)',
 '96 st (6)',
 'allerton av',
 'astor pl',
 'atlantic av-barclays ctr',
 'baychester av',
 'bedford p',
 'bergen st',
 'beverly rd',
 'bleeker st',


In [37]:
df['message'][0]

'2 trains are proceeding with delays after our crews moved a train that had its brakes activated at nereid av.'

In [492]:
df['need_3_av'] = df['message'].str.extract('({0})'.format('|'.join(irt_lookup)))
df['need_3_av'] = df['need_3_av'].str.slice(start=3)

In [39]:
df['stations'].value_counts()

14 st            2477
grand central    1963
125 st           1908
96 st            1720
atlantic av      1249
                 ... 
wtc                 2
simpson             2
rawson              1
242 st              1
van cortlandt       1
Name: stations, Length: 157, dtype: int64

In [40]:
df

date                                        subject                                            message  day_of_week  rush_hour  weekend  2  brooklyn  queens  bronx  manhattan      stations
0      9/30/2021 21:34                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0  1         0       0      1          0     nereid av
1      9/30/2021 21:28                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0  1         0       0      1          0     nereid av
2      9/30/2021 19:14                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0  1         0       0      1          0   allerton av
3      9/30/2021 19:10                          bx   2 train   delays  southbound 2 trains are delayed while we inves...            3          0        0  1         0       0      1          0   allerton av
4      9/30/2021 18:48        update : bx   2 train   trains rerouted  wakefield-bound 2 trains have resumed stopping...            3          0        0  1         0       0      1          0  bx park east
...                ...                                            ...                                                ...          ...        ...      ... ..       ...     ...    ...        ...           ...
67181    1/2/2010 8:28              qns   7 train   track maintenance  times sq-bound 7 trains operating on normal ro...            5          0        1  0         0       1      0          0           NaN
67182    1/1/2010 0:56  updated : bx   4 train   police investigation  4 train service has resumed with residual delays.            4          0        0  0         0       0      1          0           NaN
67183    1/1/2010 0:49  updated : bx   4 train   police investigation  bk-bound. 4 train express burnside av to 125 s...            4          0        0  0         0       0      1          0        161 st
67184    1/1/2010 0:35  updated : bx   4 train   police investigation  both directions. 4 train susp btwn burnside av...            4          0        0  0         0       0      1          0        161 st
67185    1/1/2010 0:26            bx   4 train   police investigation  bk-bound. 4 train via express track burnside a...            4          0        0  0         0       0      1          0        161 st

[67186 rows x 12 columns]

In [187]:
nyc = pd.read_csv('data_cleaning/nyc_weather.csv')

In [188]:
nyc

date  avg_temp  min_temp  max_temp  snowfall  snowfall_depth   prcp  avg_wind_spd fastest_wind_directions  fastest_wind_spd  major_conditions  minor_conditions  neutral_conditions  clear_conditions
0     2010-01-01      36.0      32.5      40.5      0.00             0.0  0.035         4.365                   nw, w             22.45                 1                 0                   0                 0
1     2010-01-02      25.0      17.0      33.5      0.15             0.0  0.010        18.120                   nw, w             39.95                 1                 0                   0                 0
2     2010-01-03      20.0      17.5      23.0      0.00             0.0  0.000        19.910                  nw, nw             42.95                 1                 0                   0                 0
3     2010-01-04      25.0      19.5      31.0      0.00             0.0  0.000        14.205                   nw, w             27.50                 0                 0                   0                 1
4     2010-01-05      26.0      20.5      31.0      0.00             0.0  0.000        12.860                   nw, w             26.95                 0                 0                   0                 1
...          ...       ...       ...       ...       ...             ...    ...           ...                     ...               ...               ...               ...                 ...               ...
4287  2021-09-27      69.0      61.5      79.0      0.00             0.0  0.000         9.955                    s, n             26.95                 0                 0                   0                 1
4288  2021-09-28      69.0      61.5      73.5      0.00             0.0  0.180         9.955                    w, n             26.95                 0                 0                   1                 0
4289  2021-09-29      64.0      54.0      70.0      0.00             0.0  0.000         9.955                    n, n             26.95                 0                 0                   0                 1
4290  2021-09-30      62.0      54.5      66.0      0.00             0.0  0.000         9.955                   nw, n             26.95                 0                 0                   0                 1
4291  2021-10-01      60.0      50.5      68.5      0.00             0.0  0.000         9.955                    w, n             26.95                 0                 0                   0                 1

[4292 rows x 14 columns]

In [189]:
df

103 st (7)  canal st (6)  96 st (6)  28 st (6)  23 st (6)  110 st (6)  103 st (6)  canal st (1)  23 st (1)  28 st (1)  86 st (1)  96 st (1)  110 st (1)  103 st (1)             date                                        subject                                            message  day_of_week  rush_hour  weekend  2  brooklyn  queens  bronx  manhattan      stations  103 st  110 st  111 st  116 st  125 st  135 st  137 st  138 st-grand concourse  14 st  145 st  148 st  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  23 st  233 st  238 st  241 st  242 st  28 st  33 st  34 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  86 st  90 st  96 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  burke av  burnside  bx park east  \
0               0             0          0          0          0           0           0             0          0          0          0          0           0           0  9/30/2021 21:34                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0   
1               0             0          0          0          0           0           0             0          0          0          0          0           0           0  9/30/2021 21:28                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0   
2               0             0          0          0          0           0           0             0          0          0          0          0           0           0  9/30/2021 19:14                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0  1         0       0      1          0   allerton av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0   
3               0          

In [190]:
import datetime as dt

In [193]:
nyc['date'] = pd.to_datetime(nyc['date'])

In [195]:
df['date'] = pd.to_datetime(df['date'])

In [198]:
import numpy as np

In [197]:
nyc['date'].dt.date

0       2010-01-01
1       2010-01-02
2       2010-01-03
3       2010-01-04
4       2010-01-05
           ...    
4287    2021-09-27
4288    2021-09-28
4289    2021-09-29
4290    2021-09-30
4291    2021-10-01
Name: date, Length: 4292, dtype: object

In [196]:
df['date'].dt.date

0        2021-09-30
1        2021-09-30
2        2021-09-30
3        2021-09-30
4        2021-09-30
            ...    
67181    2010-01-02
67182    2010-01-01
67183    2010-01-01
67184    2010-01-01
67185    2010-01-01
Name: date, Length: 67186, dtype: object

In [ ]:
df.merge(nyc)

In [41]:
stations = pd.get_dummies(df['stations'])

In [44]:
names = list(stations.columns)
names

['103 st',
 '110 st',
 '111 st',
 '116 st',
 '125 st',
 '135 st',
 '137 st',
 '138 st - grand concourse',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '149 st - grand concourse',
 '149 st grand concourse',
 '149 st-grand concourse',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '23 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '28 st',
 '3 av -',
 '3 av 138 st',
 '3 av-',
 '33 st',
 '34 st',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '86 st',
 '90 st',
 '96 st',
 'allerton av',
 'astor',
 'atlantic av',
 'baychester av',
 'bedford p',
 'bergen st',
 'beverly r',
 'bleeker st',
 'borough hall',
 'bowling green',
 'brook av',
 'brooklyn bridge',
 'buhre',
 'burke av',
 'burnside',
 'bx park east',
 'canal st',
 'castle hill',
 'cathedral p',
 'cham

In [45]:
def become_one(one):
    if one >= 1:
        return 1
    else:
        return 0

In [48]:
stations['138 st-grand concourse'] = stations['138 st - grand concourse'] + stations['138 st-grand concourse']
stations['138 st-grand concourse'].apply(become_one)

stations['149 st-grand concourse'] = stations['149 st-grand concourse'] + stations['149 st grand concourse'] + stations['149 st - grand concourse']
stations['149 st-grand concourse'].apply(become_one)

stations['3 av-138 st'] = stations['3 av -'] + stations['3 av-'] + stations['3 av 138 st']
stations['3 av-138 st'].apply(become_one)

stations['jackson av'] = stations['jackson'] + stations['jackson av']
stations['jackson av'].apply(become_one)

stations['mt eden'] = stations['mt eden'] + stations['mount eden']
stations['mt eden'].apply(become_one)

stations['nevins st'] = stations['nevins'] + stations['nevins st']
stations['nevins st'].apply(become_one)

stations['simpson st'] = stations['simpson'] + stations['simpson st']
stations['simpson st'].apply(become_one)

0        0
1        0
2        0
3        0
4        0
        ..
67181    0
67182    0
67183    0
67184    0
67185    0
Name: simpson st, Length: 67186, dtype: int64

In [50]:
stations.drop(['138 st - grand concourse','149 st - grand concourse','149 st grand concourse','3 av 138 st','3 av-',
                  '3 av -', 'jackson', 'mount eden', 'nevins', 'simpson'], axis=1, inplace=True)

In [52]:
df

date                                        subject                                            message  day_of_week  rush_hour  weekend  2  brooklyn  queens  bronx  manhattan      stations
0      9/30/2021 21:34                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0  1         0       0      1          0     nereid av
1      9/30/2021 21:28                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0  1         0       0      1          0     nereid av
2      9/30/2021 19:14                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0  1         0       0      1          0   allerton av
3      9/30/2021 19:10                          bx   2 train   delays  southbound 2 trains are delayed while we inves...            3          0        0  1         0       0      1          0   allerton av
4      9/30/2021 18:48        update : bx   2 train   trains rerouted  wakefield-bound 2 trains have resumed stopping...            3          0        0  1         0       0      1          0  bx park east
...                ...                                            ...                                                ...          ...        ...      ... ..       ...     ...    ...        ...           ...
67181    1/2/2010 8:28              qns   7 train   track maintenance  times sq-bound 7 trains operating on normal ro...            5          0        1  0         0       1      0          0           NaN
67182    1/1/2010 0:56  updated : bx   4 train   police investigation  4 train service has resumed with residual delays.            4          0        0  0         0       0      1          0           NaN
67183    1/1/2010 0:49  updated : bx   4 train   police investigation  bk-bound. 4 train express burnside av to 125 s...            4          0        0  0         0       0      1          0        161 st
67184    1/1/2010 0:35  updated : bx   4 train   police investigation  both directions. 4 train susp btwn burnside av...            4          0        0  0         0       0      1          0        161 st
67185    1/1/2010 0:26            bx   4 train   police investigation  bk-bound. 4 train via express track burnside a...            4          0        0  0         0       0      1          0        161 st

[67186 rows x 12 columns]

In [56]:
df = df.merge(stations, left_index=True, right_index=True)

In [60]:
irt_stations

['103 st (1)',
 '103 st (6)',
 '103 st (7)',
 '110 st (1)',
 '110 st (6)',
 '111 st',
 '116 st',
 '116 st (1)',
 '116 st (6)',
 '125 st',
 '125 st (1/2/3)',
 '125 st (4/5/6)',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '191 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '225 st',
 '23 st (1)',
 '23 st (6)',
 '231 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '28 st (1)',
 '28 st (6)',
 '3 av-138 st',
 '3 av-149 st149 st-grand concourse',
 '33 st',
 '34 st',
 '34 st-herald sq',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '86 st (1)',
 '86 st (4/5/6)',
 '90 st',
 '96 st (1)',
 '96 st (6)',
 'allerton av',
 'astor pl',
 'atlantic av-barclays ctr',
 'baychester av',
 'bedford p',
 'bergen st',
 'beverly rd',
 'bleeker st',


In [202]:
nyc.set_index('date',inplace=True)

In [204]:
nyc

avg_temp  min_temp  max_temp  snowfall  snowfall_depth   prcp  avg_wind_spd fastest_wind_directions  fastest_wind_spd  major_conditions  minor_conditions  neutral_conditions  clear_conditions
date                                                                                                                                                                                                       
2010-01-01      36.0      32.5      40.5      0.00             0.0  0.035         4.365                   nw, w             22.45                 1                 0                   0                 0
2010-01-02      25.0      17.0      33.5      0.15             0.0  0.010        18.120                   nw, w             39.95                 1                 0                   0                 0
2010-01-03      20.0      17.5      23.0      0.00             0.0  0.000        19.910                  nw, nw             42.95                 1                 0                   0                 0
2010-01-04      25.0      19.5      31.0      0.00             0.0  0.000        14.205                   nw, w             27.50                 0                 0                   0                 1
2010-01-05      26.0      20.5      31.0      0.00             0.0  0.000        12.860                   nw, w             26.95                 0                 0                   0                 1
...              ...       ...       ...       ...             ...    ...           ...                     ...               ...               ...               ...                 ...               ...
2021-09-27      69.0      61.5      79.0      0.00             0.0  0.000         9.955                    s, n             26.95                 0                 0                   0                 1
2021-09-28      69.0      61.5      73.5      0.00             0.0  0.180         9.955                    w, n             26.95                 0                 0                   1                 0
2021-09-29      64.0      54.0      70.0      0.00             0.0  0.000         9.955                    n, n             26.95                 0                 0                   0                 1
2021-09-30      62.0      54.5      66.0      0.00             0.0  0.000         9.955                   nw, n             26.95                 0                 0                   0                 1
2021-10-01      60.0      50.5      68.5      0.00             0.0  0.000         9.955                    w, n             26.95                 0                 0                   0                 1

[4292 rows x 13 columns]

In [203]:
indices = nyc.index

In [205]:
df.set_index('date',inplace=True)

In [460]:
df

96 st test  34 st-penn (1/2/3)  34 st-hudson yds (7)  gun hill rd (2/5)  gun hill rd (5)  103 st (7)  canal st (6)  96 st (6)  28 st (6)  23 st (6)  110 st (6)  103 st (6)  canal st (1)  23 st (1)  28 st (1)  86 st (1)  96 st (1)  110 st (1)  103 st (1)                                        subject                                            message  day_of_week  rush_hour  weekend  wed  brooklyn  queens  bronx  manhattan      stations  111 st  116 st  125 st  135 st  137 st  138 st-grand concourse  14 st  145 st  148 st  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  233 st  238 st  241 st  242 st  33 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  90 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  burke av  \
mon             0                   0                     0                  0                0           0             0          0          0          0           0           0             0          0          0          0          0           0           0                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0    1         0       0      1          0     nereid av       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0       0       0       0       0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0   
1               0                   0                     0                  0                0           0             0          0          0          0           0           0             0          0          0          0          0           0           0                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0    1         0       0      1          0     nereid av       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0       0       0       0       0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0   
2               0                   0                     0                  0                0           0             0          0          0          0           0           0             0          0          0          0          0           0           0                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0    1         0       0      1          0   allerton av       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0       0       0       0       0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0         0   
3               0          

In [217]:
df['datetime'] = pd.to_datetime(df.index)

In [220]:
df.drop('date1',axis=1,inplace=True)

In [223]:
df['dayz'] = df['datetime'].dt.date

In [227]:
nyc['datetime'] = pd.to_datetime(nyc.index)

In [228]:
nyc['dayz'] = nyc['datetime'].dt.date

In [231]:
df = df.merge(nyc, how='left', left_on=df['dayz'], right_on=nyc['dayz'])

In [232]:
df

key_0  103 st (7)  canal st (6)  96 st (6)  28 st (6)  23 st (6)  110 st (6)  103 st (6)  canal st (1)  23 st (1)  28 st (1)  86 st (1)  96 st (1)  110 st (1)  103 st (1)                                        subject                                            message  day_of_week  rush_hour  weekend  2  brooklyn  queens  bronx  manhattan      stations  103 st  110 st  111 st  116 st  125 st  135 st  137 st  138 st-grand concourse  14 st  145 st  148 st  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  23 st  233 st  238 st  241 st  242 st  28 st  33 st  34 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  86 st  90 st  96 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  burke av  burnside  bx park east  canal st  \
0      2021-09-30           0             0          0          0          0           0           0             0          0          0          0          0           0           0                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0   
1      2021-09-30           0             0          0          0          0           0           0             0          0          0          0          0           0           0                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0   
2      2021-09-30           0             0          0          0          0           0           0             0          0          0          0          0           0           0                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0  1         0       0      1          0   allerton av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0   
3      2021-

In [233]:
df

key_0  103 st (7)  canal st (6)  96 st (6)  28 st (6)  23 st (6)  110 st (6)  103 st (6)  canal st (1)  23 st (1)  28 st (1)  86 st (1)  96 st (1)  110 st (1)  103 st (1)                                        subject                                            message  day_of_week  rush_hour  weekend  2  brooklyn  queens  bronx  manhattan      stations  103 st  110 st  111 st  116 st  125 st  135 st  137 st  138 st-grand concourse  14 st  145 st  148 st  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  23 st  233 st  238 st  241 st  242 st  28 st  33 st  34 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  86 st  90 st  96 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  burke av  burnside  bx park east  canal st  \
0      2021-09-30           0             0          0          0          0           0           0             0          0          0          0          0           0           0                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0   
1      2021-09-30           0             0          0          0          0           0           0             0          0          0          0          0           0           0                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0  1         0       0      1          0     nereid av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0   
2      2021-09-30           0             0          0          0          0           0           0             0          0          0          0          0           0           0                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0  1         0       0      1          0   allerton av       0       0       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0   
3      2021-

In [241]:
names = list(irt_stations_df)

In [242]:
names

['103 st (1)',
 '103 st (6)',
 '103 st (7)',
 '110 st (1)',
 '110 st (6)',
 '111 st',
 '116 st',
 '116 st (1)',
 '116 st (6)',
 '125 st',
 '125 st (1/2/3)',
 '125 st (4/5/6)',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '191 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '225 st',
 '23 st (1)',
 '23 st (6)',
 '231 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '28 st (1)',
 '28 st (6)',
 '3 av-138 st',
 '3 av-149 st149 st-grand concourse',
 '33 st',
 '34 st',
 '34 st-herald sq',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '86 st (1)',
 '86 st (4/5/6)',
 '90 st',
 '96 st (1)',
 '96 st (6)',
 'allerton av',
 'astor pl',
 'atlantic av-barclays ctr',
 'baychester av',
 'bedford p',
 'bergen st',
 'beverly rd',
 'bleeker st',


In [463]:
st_1 = df.loc[df['subject'].str.contains('1 ')]
st_2 = df.loc[df['subject'].str.contains('2 ')]
st_3 = df.loc[df['subject'].str.contains('3 ')]
st_4 = df.loc[df['subject'].str.contains('4 ')]
st_5 = df.loc[df['subject'].str.contains('5 ')]
st_6 = df.loc[df['subject'].str.contains('6 ')]
st_5n2 = st_5.loc[~st_5['subject'].str.contains('2 ')]
st_25 = df.loc[df['subject'].str.contains('2|5')]
st_7 = df.loc[df['subject'].str.contains('7 ')]
st_123 = df.loc[df['subject'].str.contains('1 |2 |3 ')]

In [279]:
st_1_st = st_1[['125 st', '86 st']]
st_6_st = st_6[['125 st', '86 st']]

In [347]:
st_2_st = st_2[['gun hill', '125 st', 'fulton st', 'wall st']]

In [253]:
st_3_st = st_3[['125 st', 'fulton st', 'wall st']]

In [254]:
st_4_st = st_4[['125 st', '86 st', 'fulton st', 'wall st']]

In [255]:
st_5_st = st_5[['125 st', '86 st', 'fulton st', 'wall st']]

In [343]:
st_5n2_st = st_5n2[['gun hill', '86 st']]

In [257]:
st_25_st = st_25[['gun hill', '86 st']]

In [396]:
st_7_st = st_7[['33 st','34 st']]

In [467]:
st_123_st = st_123[['33 st', '96 st test']]

In [482]:
irt_lookup

['at van cortlandt',
 'at 242 st',
 'at 238 st',
 'at 231 st',
 'at 225 st',
 'at 215 st',
 'at 207 st',
 'at dyckman st',
 'at 191 st',
 'at 181 st',
 'at 168 st',
 'at 157 st',
 'at 145 st',
 'at 137 st',
 'at 125 st',
 'at 116 st',
 'at 110 st',
 'at 103 st',
 'at 96 st',
 'at 86 st',
 'at 79 st',
 'at 72 st',
 'at 66 st',
 'at columbus',
 'at 50 st',
 'at times sq',
 'at 34 st',
 'at 28 st',
 'at 23 st',
 'at 18 st',
 'at 14 st',
 'at christopher st',
 'at houston st',
 'at canal st',
 'at franklin st',
 'at chambers st',
 'at wtc',
 'at rector st',
 'at ferry',
 'at 241 st',
 'at nereid av',
 'at 233 st',
 'at 225 st',
 'at 219 st',
 'at gun hill',
 'at burke av',
 'at allerton av',
 'at pelham p',
 'at bx park east',
 'at e 180',
 'at e 178',
 'at 174 st',
 'at freeman st',
 'at simpson st',
 'at intervale av',
 'at prospect av',
 'at jackson av',
 'at 3 av-',
 'at 3 av -',
 'at 149 st-grand concourse',
 'at 149 st - grand concourse',
 'at 149 st grand concourse',
 'at 135 st',
 

In [481]:
names

['103 st (1)',
 '103 st (6)',
 '103 st (7)',
 '110 st (1)',
 '110 st (6)',
 '111 st',
 '116 st',
 '116 st (1)',
 '116 st (6)',
 '125 st',
 '125 st (1/2/3)',
 '125 st (4/5/6)',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '191 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '225 st',
 '23 st (1)',
 '23 st (6)',
 '231 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '28 st (1)',
 '28 st (6)',
 '3 av-138 st',
 '3 av-149 st149 st-grand concourse',
 '33 st',
 '34 st',
 '34 st-herald sq',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '86 st (1)',
 '86 st (4/5/6)',
 '90 st',
 '96 st (1)',
 '96 st (6)',
 'allerton av',
 'astor pl',
 'atlantic av-barclays ctr',
 'baychester av',
 'bedford p',
 'bergen st',
 'beverly rd',
 'bleeker st',


In [468]:
train_123_st = st_123_st.loc[st_123_st['3 av-'] == 1]
indices = train_123_st.index
train_123_st

33 st  96 st test
26         0           1
27         0           1
28         0           1
60         0           1
63         0           1
...      ...         ...
61958      0           1
62288      0           1
62301      0           1
62453      0           1
62985      0           1

[1456 rows x 2 columns]

In [469]:
df.insert(loc=0, column='96 st (1/2/3)',value=0)

In [470]:
df.loc[indices, '96 st (1/2/3)'] = 1

In [471]:
df['96 st (1/2/3)'].value_counts()

0    65730
1     1456
Name: 96 st (1/2/3), dtype: int64

In [352]:
df['125 st (4/5/6)'] = (df['125 st (4)'] + df['125 st (5)'] + df['125 st (6)'])
df['125 st (4/5/6)'].apply(become_one)

df['wall st (4/5)'] = (df['wall st (4)'] + df['wall st (5)'])
df['wall st (4/5)'].apply(become_one)

df['fulton st (4/5)'] = (df['fulton st (4)'] + df['fulton st (5)'])
df['fulton st (4/5)'].apply(become_one)

df['86 st (4/5/6)'] = (df['86 st (4)'] + df['86 st (5)'] + df['86 st (6)'])
df['86 st (4/5/6)'].apply(become_one)

df['125 st (1/2/3)'] = (df['125 st (1)'] + df['125 st (2)'] + df['125 st (3)'])
df['125 st (1/2/3)'].apply(become_one)

df['fulton st (2/3)'] = (df['fulton st (2)'] + df['fulton st (3)'])
df['fulton st (2/3)'].apply(become_one)

df['wall st (2/3)'] = (df['wall st (2)'] + df['wall st (3)'])
df['wall st (2/3)'].apply(become_one)

0        0
1        0
2        0
3        0
4        0
        ..
67181    0
67182    0
67183    0
67184    0
67185    0
Name: wall st (2/3), Length: 67186, dtype: int64

In [354]:
df.drop(['wall st (4)', 'wall st (5)','fulton st (4)', 'fulton st (5)','wall st (2)','wall st (3)',
        '125 st (4)', '125 st (5)', '125 st (6)','125 st (1)', '125 st (2)', '125 st (3)', 'fulton st (2)', 'fulton st (3)'
        ], axis=1, inplace=True)

In [356]:
df.drop(['86 st (4)', '86 st (5)', '86 st (6)'], axis=1, inplace=True)

In [493]:
df

3 av-149 st (2/5)  96 st (1/2/3)  34 st-penn (1/2/3)  34 st-hudson yds (7)  gun hill rd (2/5)  gun hill rd (5)  103 st (7)  canal st (6)  96 st (6)  28 st (6)  23 st (6)  110 st (6)  103 st (6)  canal st (1)  23 st (1)  28 st (1)  86 st (1)  110 st (1)  103 st (1)                                        subject                                            message  day_of_week  rush_hour  weekend  wed  brooklyn  queens  bronx  manhattan      stations  111 st  116 st  125 st  135 st  137 st  138 st-grand concourse  14 st  145 st  148 st  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  233 st  238 st  241 st  242 st  33 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  90 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  \
mon                    0              0                   0                     0                  0                0           0             0          0          0          0           0           0             0          0          0          0           0           0                 update : bx   2 train   delays  2 trains are proceeding with delays after our ...            3          0        0    1         0       0      1          0     nereid av       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0       0       0       0       0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0   
1                      0              0                   0                     0                  0                0           0             0          0          0          0           0           0             0          0          0          0           0           0                          bx   2 train   delays  2 trains are delayed in both directions while ...            3          0        0    1         0       0      1          0     nereid av       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0       0       0       0       0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0   
2                      0              0                   0                     0                  0                0           0             0          0          0          0           0           0             0          0          0          0           0           0                 update : bx   2 train   delays  southbound 2 trains are proceeding after we mo...            3          0        0    1         0       0      1          0   allerton av       0       0       0       0       0                       0      0       0       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0       0       0       0       0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0   
3                      

In [494]:
av_3 = pd.get_dummies(df['need_3_av'])

In [495]:
av_3

103 st  110 st  111 st  116 st  125 st  135 st  137 st  138 st - grand concourse  138 st-grand concourse  14 st  145 st  148 st  149 st - grand concourse  149 st grand concourse  149 st-grand concourse  157 st  161 st  167 st  168 st  170 st  174 st  176 st  18 st  181 st  183 st  207 st  215 st  219 st  225 st  23 st  233 st  238 st  241 st  242 st  28 st  3 av -  3 av - 149  3 av 138 st  3 av-  3 av- 149  3 av-149  33 st  34 st  40 st  46 st  5 av  50 st  51 st  52 st  59 st  61 st  66 st  68 st  69 st  72 st  74 st  77 st  79 st  82 st  86 st  90 st  96 st  allerton av  astor  atlantic av  baychester av  bedford p  bergen st  beverly r  bleeker st  borough hall  bowling green  brook av  brooklyn bridge  buhre  burke av  burnside  bx park east  canal st  castle hill  cathedral p  chambers st  christopher st  church av  clark st  court sq  crown heights  cypress av  dyckman st  e 143  e 149  e 180  eastchester  eastern p  elder av  flatbush av  flushing  fordham  franklin av  \
mon         0       0       0       0       0       0       0                         0                       0      0       0       0                         0                       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0       0           0            0      0          0         0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0            0            0            0               0          0         0         0              0           0           0      0      0      0            0          0         0            0         0        0            0   
1           0       0       0       0       0       0       0                         0                       0      0       0       0                         0                       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0       0           0            0      0          0         0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            0      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0            0            0            0               0          0         0         0              0           0           0      0      0      0            0          0         0            0         0        0            0   
2           0       0       0       0       0       0       0                         0                       0      0       0       0                         0                       0                       0       0       0       0       0       0       0       0      0       0       0       0       0       0       0      0       0       0       0       0      0       0           0            0      0          0         0      0      0      0      0     0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0      0            1      0            0              0          0          0          0           0             0              0         0                0      0         0         0             0         0            0            0            0               0          0         0         0              0           0           0      0      0      0            0          0         0            0         0        0            0   
3  

In [497]:
stations_3av = av_3[['3 av-149', '3 av- 149','3 av - 149']]

In [498]:
stations_3av

3 av-149  3 av- 149  3 av - 149
mon           0          0           0
1             0          0           0
2             0          0           0
3             0          0           0
4             0          0           0
...         ...        ...         ...
67181         0          0           0
67182         0          0           0
67183         0          0           0
67184         0          0           0
67185         0          0           0

[67186 rows x 3 columns]

In [500]:
stations_3av['3 av-149 st'] = stations_3av['3 av-149'] + stations_3av['3 av- 149'] + stations_3av['3 av - 149']
stations_3av['3 av-149 st'].apply(become_one)

<ipython-input-500-edfe81a7e87b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stations_3av['3 av-149 st'] = stations_3av['3 av-149'] + stations_3av['3 av- 149'] + stations_3av['3 av - 149']


mon      0
1        0
2        0
3        0
4        0
        ..
67181    0
67182    0
67183    0
67184    0
67185    0
Name: 3 av-149 st, Length: 67186, dtype: int64

In [361]:
day_of_week = pd.get_dummies(df['day_of_week'])

In [365]:
df.drop(['key_0','datetime_x','dayz_x','datetime_y', 'dayz_y'],axis=1,inplace=True)

In [370]:
df = df.merge(day_of_week, left_index=True, right_index=True)

In [380]:
df.rename(columns={0:'mon',1:'tue',2:'wed',3:'th',4:'fri',5:'sat',6:'sun'},inplace=True)

In [384]:
with open('model_data.pkl','wb') as f:
    pkl.dump(df, f)

In [408]:
cols = df.columns

In [389]:
df.drop(['103 st','canal st', 'gun hill', '96 st','28 st','23 st','86 st','110 st'], axis=1,inplace=True)

In [ ]:
df.rename(columns={'111 st':'111 st (7)','junction b':'junction blvd (7)','mets':'mets willis pt (7)',
                  '90 st':'90 st (7)', '82 st':'82 st (7)', '74 st':'74 st (7)', '69 st': '69 st (7)',
                  '61 st': '61 st (7)', '52 st': '52 st (7)', '46 st': '46 st (7)', '40 st': '40 st (7)',
                  'rawson':'33 st-rawson st (7)', 'qnsboro pl': 'qnsboro plza (7)', 'court sq': 'court sq (7)',
                  'hunters p': 'hunters pt (7)','grand central':'42 st-grand central (4/5/6/7)',
                   'times sq':'42 st-times sq (2/3/4/5/6/7)','van cortlandt':'van cortlandt park (1)',
                  '238 st':'238 st (1)', '231 st': '231 st (1)', '225 st': 'marble hill-225 st (1)',
                  '215 st':'215 st (1)', '207 st': '207 st (1)', 'dyckman st':'dyckman st (1)',
                  '191 st':'191 st (1)','181 st':'181 st (1)', '168 st': '168 st (1)','157 st':'157 st (1)',
                  '145 st':'145 st (1)','137 st':'137 st (1)','125 st':'125 st (1)','116 st':'116 st-columbia (1)',
                  'cathedral p':'110 st-cathedral pkwy (1)', '103 st':'103 st (1)', '96 st', '96 st (1/2/3)',
                  '})

In [394]:
stations_7

['flushing',
 'mets',
 '111 st',
 '103 st',
 'junction b',
 '90 st',
 '82 st',
 '74 st',
 '69 st',
 '61 st',
 '52 st',
 '46 st',
 '40 st',
 'rawson',
 'qnsboro pl',
 'court sq',
 'hunters p',
 'vernon b',
 'grand central',
 '5 av',
 'times sq',
 '34 st h',
 '34 st-h',
 '34 st- h',
 '34 st - h']

In [409]:
list(cols)

['34 st-penn (1/2/3)',
 '34 st-hudson yds (7)',
 'gun hill rd (2/5)',
 'gun hill rd (5)',
 '103 st (7)',
 'canal st (6)',
 '96 st (6)',
 '28 st (6)',
 '23 st (6)',
 '110 st (6)',
 '103 st (6)',
 'canal st (1)',
 '23 st (1)',
 '28 st (1)',
 '86 st (1)',
 '96 st (1)',
 '110 st (1)',
 '103 st (1)',
 'subject',
 'message',
 'day_of_week',
 'rush_hour',
 'weekend',
 'wed',
 'brooklyn',
 'queens',
 'bronx',
 'manhattan',
 'stations',
 '111 st',
 '116 st',
 '125 st',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '149 st-grand concourse',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '33 st',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '90 st',
 'allerton av',
 'astor',
 'atlantic av',
 'bayches

In [407]:
df.drop('34 st',axis=1,inplace=True)

In [431]:
stations_96 = (stations.loc[stations['96 st'] == 1])

In [433]:
stations_96 = stations_96[['96 st','103 st']]

In [452]:
stations_96

96 st  103 st
26         1       0
27         1       0
28         1       0
60         1       0
63         1       0
...      ...     ...
63164      1       0
63528      1       0
63529      1       0
63693      1       0
65410      1       0

[1720 rows x 2 columns]

In [502]:
st_3av = (stations_3av.loc[stations_3av['3 av-149 st'] == 1])

In [503]:
st_3av

3 av-149  3 av- 149  3 av - 149  3 av-149 st
78            1          0           0            1
79            1          0           0            1
97            1          0           0            1
98            1          0           0            1
144           1          0           0            1
...         ...        ...         ...          ...
58119         1          0           0            1
58120         1          0           0            1
60872         0          1           0            1
61536         1          0           0            1
64071         0          1           0            1

[471 rows x 4 columns]

In [443]:
indices = st_3av.index

In [504]:
train_123_st = st_3av.loc[st_3av['3 av-149 st'] == 1]
indices = train_123_st.index
train_123_st

3 av-149  3 av- 149  3 av - 149  3 av-149 st
78            1          0           0            1
79            1          0           0            1
97            1          0           0            1
98            1          0           0            1
144           1          0           0            1
...         ...        ...         ...          ...
58119         1          0           0            1
58120         1          0           0            1
60872         0          1           0            1
61536         1          0           0            1
64071         0          1           0            1

[471 rows x 4 columns]

In [480]:
df.insert(loc=0, column='3 av-149 st (2/5)',value=0)

In [505]:
df.loc[indices, '3 av-149 st (2/5)'] = 1

In [507]:
df.drop('need_3_av',axis=1,inplace=True)

In [457]:
df['96 st test']

mon      0
1        0
2        0
3        0
4        0
        ..
67181    0
67182    0
67183    0
67184    0
67185    0
Name: 96 st test, Length: 67186, dtype: int64

In [458]:
df['96 st'].value_counts()

0    64849
1     2337
Name: 96 st, dtype: int64

In [473]:
df.drop(['96 st test', '96 st'],axis=1,inplace=True)

In [478]:
cols = df.columns

In [477]:
# df['96 st (1/2/3)'] = df['96 st (1/2/3)'] + df['96 st (1)']
# df['96 st (1/2/3)'].apply(become_one)
# df.drop('96 st (1)',axis=1,inplace=True)

In [479]:
list(cols)

['96 st (1/2/3)',
 '34 st-penn (1/2/3)',
 '34 st-hudson yds (7)',
 'gun hill rd (2/5)',
 'gun hill rd (5)',
 '103 st (7)',
 'canal st (6)',
 '96 st (6)',
 '28 st (6)',
 '23 st (6)',
 '110 st (6)',
 '103 st (6)',
 'canal st (1)',
 '23 st (1)',
 '28 st (1)',
 '86 st (1)',
 '110 st (1)',
 '103 st (1)',
 'subject',
 'message',
 'day_of_week',
 'rush_hour',
 'weekend',
 'wed',
 'brooklyn',
 'queens',
 'bronx',
 'manhattan',
 'stations',
 '111 st',
 '116 st',
 '125 st',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '149 st-grand concourse',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '33 st',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '90 st',
 'allerton av',
 'astor',
 'atlantic av',
 'bay

In [476]:
names

['103 st (1)',
 '103 st (6)',
 '103 st (7)',
 '110 st (1)',
 '110 st (6)',
 '111 st',
 '116 st',
 '116 st (1)',
 '116 st (6)',
 '125 st',
 '125 st (1/2/3)',
 '125 st (4/5/6)',
 '135 st',
 '137 st',
 '138 st-grand concourse',
 '14 st',
 '145 st',
 '148 st',
 '157 st',
 '161 st',
 '167 st',
 '168 st',
 '170 st',
 '174 st',
 '176 st',
 '18 st',
 '181 st',
 '183 st',
 '191 st',
 '207 st',
 '215 st',
 '219 st',
 '225 st',
 '225 st',
 '23 st (1)',
 '23 st (6)',
 '231 st',
 '233 st',
 '238 st',
 '241 st',
 '242 st',
 '28 st (1)',
 '28 st (6)',
 '3 av-138 st',
 '3 av-149 st149 st-grand concourse',
 '33 st',
 '34 st',
 '34 st-herald sq',
 '40 st',
 '46 st',
 '5 av',
 '50 st',
 '51 st',
 '52 st',
 '59 st',
 '61 st',
 '66 st',
 '68 st',
 '69 st',
 '72 st',
 '74 st',
 '77 st',
 '79 st',
 '82 st',
 '86 st (1)',
 '86 st (4/5/6)',
 '90 st',
 '96 st (1)',
 '96 st (6)',
 'allerton av',
 'astor pl',
 'atlantic av-barclays ctr',
 'baychester av',
 'bedford p',
 'bergen st',
 'beverly rd',
 'bleeker st',


In [509]:
df.rename(columns={'111 st':'111 st (7)','junction b':'junction blvd (7)','mets':'mets willis pt (7)',
                  '90 st':'90 st (7)', '82 st':'82 st (7)', '74 st':'74 st (7)', '69 st': '69 st (7)',
                  '61 st': '61 st (7)', '52 st': '52 st (7)', '46 st': '46 st (7)', '40 st': '40 st (7)',
                  'rawson':'33 st-rawson st (7)', 'qnsboro pl': 'qnsboro plza (7)', 'court sq': 'court sq (7)',
                  'hunters p': 'hunters pt (7)','grand central':'42 st-grand central (4/5/6/7)',
                   'times sq':'42 st-times sq (2/3/4/5/6/7)','van cortlandt':'van cortlandt park (1)',
                  '238 st':'238 st (1)', '231 st': '231 st (1)', '225 st': 'marble hill-225 st (1)',
                  '215 st':'215 st (1)', '207 st': '207 st (1)', 'dyckman st':'dyckman st (1)',
                  '191 st':'191 st (1)','181 st':'181 st (1)', '168 st': '168 st (1)','157 st':'157 st (1)',
                  '145 st':'145 st (1)','137 st':'137 st (1)','125 st':'125 st (1)','116 st':'116 st-columbia (1)',
                  'cathedral p':'110 st-cathedral pkwy (1)', '103 st':'103 st (1)', '18 st':'18 st (1)',
                  '14 st':'14 st-7 av (1/2/3)','union sq':'14 st-union sq (4/5/6)','christopher st':'christopher st (1)',
                  'houston st':'houston st (1)', 'franklin st':'franklin st (1)', 'chambers st':'chambers st (1/2/3)',
                  'wtc':'wtc cortlandt (1)', 'rector st':'rector st (1)', 'ferry':'south ferry (1)','241 st':'wakefield-241 st (2/5)',
                  'nereid av':'nereid av (2/5)', '233 st':'233 st (2/5)', '225 st': '225 st (2/5)', '219 st': '219 st (2/5)',
                  'burke av': 'burke av (2/5)', 'allerton av':'allerton av (2/5)', 'pelham p':'pelham pkwy (2/5)',
                  'bx park east':'bronx park east (2/5)', 'e 180':'e 180 st (2/5)', 'west farms':'west farm sq (2/5)',
                  '174 st':'174 st (2/5)','freeman st':'freeman st (2/5)','simpson st':'simpson st (2/5)',
                  'intervale av':'interval av (2/5)', 'prospect av':'prospect av (2/5)', 'jackson av':'jackson av (2/5)'},inplace=True)

In [511]:
with open('irt.pkl', 'wb') as f:
    pkl.dump(df, f)